[package]
name = "irc-log-manager"
version = "0.1.0"
authors = ["Hyeon Kim <simnalamburt@gmail.com>"]
edition = "2018"
license = "GPL-3.0"

[dependencies]
clap = "2"
failure = "0.1"
rayon = "1"
regex = "1"
memmap = "0.7"
